### ISSUE TITLE
Markers Arguments in Shortcode

### ISSUE THREAD

**Issue by rudytoe** [marcpabst/hugo-maps#3]
Hello,

I am trying to pass markers as shortcode arguments, but I can't figure out if this is possible/what syntax to use.

```
{{< map name="my_map" markers=" - location: [-0.127758, 51.507351]     text: 'Welcome to London'" >}}
``` 

Results in:

```
execute of template failed at <$mapparams.markers>: range can’t iterate over  - location: [-0.127758, 51.507351]     text: 'Welcome to London'
```

**Comment by rudytoe** [comment]
Essentially, I'm trying to update markers for each page, not in the global config file. I tried putting different markers in the param in the front matter, but the maps don't update accordingly.

https://gohugo.io/methods/page/param/

```
---
title: "Hugo Maps"
date: 2020-05-01T00:00:00+01:00
draft: false
params:
  hugo-maps:
      test_map:
        center: [121.53737811422849, 25.04960023576451]
        zoom: 12
        interactive: false
        navigationControl: false
        markers:
          - location: [122.52170849490979, 25.04960605291676]
            text: "testing markers in frontmatter"
---
{{< map name="test_map" >}}
```
Gives this error:
```
Error: Map nametest_mapnot found in config. Please check your config file.
```
